# Generated by Django 4.2 on 2023-05-11 13:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/avatars')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=True)),
                ('isApproved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('etat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('enrolled', models.BooleanField(default=False)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.formation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default='uploads/avatars/paiperleck.jpg', null=True, upload_to='uploads/avatars')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('APIElearning.user',),
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APIElearning.media')),
                ('file', models.FileField(default=None, null=True, upload_to='uploads/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])])),
            ],
            bases=('APIElearning.media',),
        ),
        migrations.CreateModel(
            name='LinkSource',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APIElearning.media')),
                ('link', models.TextField()),
            ],
            bases=('APIElearning.media',),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RESPO', 'Respo'), ('SUPERADMIN', 'Superadmin')], default='ADMIN', max_length=10)),
                ('etat', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('APIElearning.user',),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='APIElearning.media')),
                ('file', models.FileField(default=None, null=True, upload_to='uploads/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['Mov', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            bases=('APIElearning.media',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tempdepassage', models.DurationField(default=datetime.timedelta(0))),
                ('difficulter', models.CharField(default='facile', max_length=200)),
                ('seuil', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('objectif', models.CharField(max_length=200)),
                ('nombredequestion', models.IntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('question', models.JSONField()),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('idResult', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(default='facile', max_length=200)),
                ('valider', models.BooleanField(default=False)),
                ('scoreByChap', models.JSONField()),
                ('date_de_passage', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.FloatField(default=0)),
                ('tentative', models.IntegerField(default=0)),
                ('idTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.test')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('etat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module'),
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('idCertificat', models.AutoField(primary_key=True, serialize=False)),
                ('certificat_file', models.FileField(default=None, null=True, upload_to='uploads/certificats/')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('idResultat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIElearning.resultat')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.apprenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressContenuModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.BooleanField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.media')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.apprenant')),
            ],
        ),
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progres', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.apprenant')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.responsable'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField()),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.apprenant')),
            ],
        ),
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.BooleanField(default=False)),
                ('encours', models.BooleanField(default=True)),
                ('refus', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.module')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIElearning.apprenant')),
            ],
        ),
    ]
