# Generated by Django 4.2 on 2023-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIElearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='lienPPT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RESPO', 'Respo'), ('MASTER', 'Master'), ('SUPERADMIN', 'Superadmin')], default='ADMIN', max_length=10),
        ),
    ]
